# Generated by Django 3.1.7 on 2021-05-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0002_alter_proreview_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proreview',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
