# Generated by Django 3.1.7 on 2021-05-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20210521_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
