# Generated by Django 3.1.7 on 2021-05-25 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20210525_0920'),
        ('community', '0007_auto_20210525_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='movie_title',
        ),
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
            preserve_default=False,
        ),
    ]
