# Generated by Django 3.2.1 on 2021-05-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_rank',
            field=models.IntegerField(default=0),
        ),
    ]
