# Generated by Django 3.1.7 on 2021-05-22 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210521_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.BooleanField(default=False)),
                ('action', models.BooleanField(default=False)),
                ('adventure', models.BooleanField(default=False)),
                ('animation', models.BooleanField(default=False)),
                ('comedy', models.BooleanField(default=False)),
                ('crime', models.BooleanField(default=False)),
                ('documentary', models.BooleanField(default=False)),
                ('drama', models.BooleanField(default=False)),
                ('family', models.BooleanField(default=False)),
                ('fantasy', models.BooleanField(default=False)),
                ('history', models.BooleanField(default=False)),
                ('horror', models.BooleanField(default=False)),
                ('music', models.BooleanField(default=False)),
                ('mystery', models.BooleanField(default=False)),
                ('romance', models.BooleanField(default=False)),
                ('science_fiction', models.BooleanField(default=False)),
                ('tv_movie', models.BooleanField(default=False)),
                ('thriller', models.BooleanField(default=False)),
                ('war', models.BooleanField(default=False)),
                ('western', models.BooleanField(default=False)),
                ('review_stamp', models.BooleanField(default=False)),
                ('comment_stamp', models.BooleanField(default=False)),
                ('follower_stamp', models.BooleanField(default=False)),
                ('joined_stamp', models.BooleanField(default=False)),
                ('all_stamp', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
