# Generated by Django 3.1.7 on 2021-05-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210524_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default='2999-01-01'),
        ),
    ]
